version: "2.1"

services:
  activemq:
    image: pandorasystems/activemq
    container_name: activemq
    ports:
      - "61616:61616"
      - "8181:8181"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://activemq:8181/activemqweb"]
      interval: 45s
      timeout: 20s
      retries: 10

  apix:
    image: pandorasystems/apix
    container_name: apix
    env_file: apix.env
    ports:
      - "8001:80"
      - "8081:8081"
      - "5011:5011"
    depends_on:
      - fcrepo
    healthcheck:
      test: ["CMD", "/usr/local/bin/docker-healthcheck.sh"]
      interval: 45s
      timeout: 20s
      retries: 1

  apix-sparqler-public-api:
    image: pandorasystems/apix-sparqler-public-api
    container_name: apix-sparqler-public-api
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy

  exts-sparqler:
    image: pandorasystems/exts-sparqler
    container_name: exts-sparqler
    ports:
      - "9104:9104"
      - "5008:5008"
    environment:
      - FCREPO_BASEURI=http4://fcrepo:8080/fcrepo/rest
      - FUSEKI_BASEURI=http4://fuseki:3030
    depends_on:
      apix:
        condition: service_healthy

  fcrepo:
    image: pandorasystems/fcrepo:4.8.1
    container_name: fcrepo
    environment:
      CATALINA_OPTS: -Dfcrepo.home=/mnt/fcrepo-data -Dfcrepo.spring.configuration=file:/etc/spring/fcrepo-config.xml -Xss8M
    ports:
      - "8080:8080"
    depends_on:
      activemq:
        condition: service_healthy
    volumes:
      - fcrepo-volume:/mnt/fcrepo-data

  fuseki:
    image: pandorasystems/fuseki:2.4.4
    container_name: fuseki
    environment:
        CATALINA_OPTS: -Xmx8G -Xss8M
    ports:
      - "3030:3030"
    volumes:
      - fuseki-volume:/shared

  image-services:
    image: pandorasystems/image-services
    container_name: image-services
    ports:
      - "9105:9105"
    depends_on:
      apix:
        condition: service_healthy
    links:
      - fcrepo:localhost
    volumes:
      - loris-volume:/tmp/binaries

  loris:
    image: pandorasystems/loris:2.1.1
    container_name: loris
    env_file: apix.env
    ports:
      - "5004:5004"
    volumes:
      - loris-volume:/tmp/binaries
      - loris-cache:/tmp/loris/cache

#  loris2:
#    image: pandorasystems/loris:2.1.0
#    container_name: loris2
#    env_file: apix.env
#    ports:
#      - "5005:5004"
#    volumes:
#      - loris-volume:/tmp/binaries
#      - loris-cache:/tmp/loris/loris

  messaging:
    image: pandorasystems/messaging
    container_name: messaging
    env_file: apix.env
    ports:
      - "9080:9080"
    environment:
      - FCREPO_BASEURI=http4://localhost:8080/fcrepo/rest
      - FUSEKI_BASEURI=http4://fuseki:3030/fuseki/manifests

    depends_on:
      - fcrepo
    links:
      - fcrepo:localhost

  mirador:
    image: pandorasystems/mirador:2.1.2
    container_name: mirador
    env_file: apix.env
#    environment:
#      - ANNOTATION_SERVER_HOST=anno.b-ol.de
    ports:
      - "8000:8000"

  redis:
    image: pandorasystems/redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "/usr/local/bin/docker-healthcheck.sh"]
      interval: 45s
      timeout: 20s
      retries: 1

  uv-webapp:
    image: pandoraframework/uv-webapp:2.0.0
    container_name: uv-webapp
    env_file: apix.env
    ports:
      - "9001:9001"

volumes:
  fcrepo-volume:
    driver_opts:
          type: none
          device: /mnt/pandora-data/fcrepo-data
          o: bind
  loris-cache:
  loris-volume:
    driver_opts:
          type: none
          device: /mnt/pandora-data/loris/binaries
          o: bind
  fuseki-volume:
    driver_opts:
          type: none
          device: /mnt/pandora-data/fuseki
          o: bind